name: Build Kernel - A12

on:
  workflow_dispatch:
    inputs:
      KERNEL_REPO:
        description: 'Link repo kernel'
        required: true
        default: 'https://github.com/TegarXLu/Templar-Kernel-GKI-5.10'
      KERNEL_BRANCH:
        description: 'Branch kernel'
        required: true
        default: 'main'

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  push:
    paths:
      - .github/workflows/main.yml  # Runs when this workflow file is updated\
  workflow_dispatch:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true

jobs:
  build-kernels-a12:
    strategy:
      fail-fast: true
      matrix:
        include:
        - sub_level: "X"
          os_patch_level: "lts"
          revision: "r1"
    uses: ./.github/workflows/gki.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
